// Skeleton for depth_blend.comp (paraLLEl-RDP)
//
// PURPOSE: Per-tile depth test, blending, and write-back to RDRAM staging buffers.
//          This shader is dispatched indirectly once per tile that has rasterised data.
//
// TODO: Replace fn main() stub with Naga-transpiled WGSL from depth_blend.comp.
//       Build step: tools/transpile-shaders.sh
//
// NOTE: depth_blend uses subgroup operations (GL_KHR_shader_subgroup_*).
//       WGSL subgroup support is behind the "chromium-experimental-subgroups" feature.
//       The transpiled version should check for subgroup availability and provide
//       a fallback path without subgroups.
//
// Binding layout (group 0):
//   binding(0-2) - VRAM, HiddenVRAM, TMEM  (from data_structures_buffers.h)
//   binding(3)   - colour buffer (from rasterizer output)
//   binding(4)   - depth buffer
//   binding(5)   - shade-alpha buffer
//   binding(6)   - coverage buffer
//   binding(7)   - tile instance offsets
// set(1):  TriangleSetup, Attribute, Derived, Scissor, StaticRaster, DepthBlend,
//          StateIndices, TileInfo, SpanSetups, SpanOffsets, BlenderLUT, TileBinning*2
// set(2):  GlobalConstants UBO
// Push constants → group(3) binding(0)

struct DepthBlendRegs {
    fb_addr_index       : u32,
    fb_depth_addr_index : u32,
    fb_width            : u32,
    fb_height           : u32,
    group_mask          : u32,
    _pad0               : u32,
    _pad1               : u32,
    _pad2               : u32,
}

// Minimal set-0 bindings needed to compile:
@group(0) @binding(0) var<storage, read_write> rdram        : array<u32>;
@group(0) @binding(1) var<storage, read_write> hidden_rdram : array<u32>;
@group(0) @binding(2) var<storage, read_write> tmem         : array<u32>;
@group(0) @binding(3) var<storage, read>       color_buf    : array<u32>;
@group(0) @binding(4) var<storage, read>       depth_buf    : array<i32>;
@group(0) @binding(5) var<storage, read>       shade_alpha  : array<u32>;
@group(0) @binding(6) var<storage, read>       coverage     : array<u32>;
@group(0) @binding(7) var<storage, read>       tile_offsets : array<u32>;

@group(3) @binding(0) var<uniform> regs: DepthBlendRegs;

@compute @workgroup_size(8, 8, 1)
fn main(
    @builtin(global_invocation_id) gid: vec3<u32>,
    @builtin(workgroup_id)         wg_id: vec3<u32>,
) {
    // STUB: Full implementation generated by tools/transpile-shaders.sh from depth_blend.comp
    _ = gid;
    _ = wg_id;
}
