// Skeleton for rasterizer.comp (paraLLEl-RDP)
//
// PURPOSE: Rasterise triangles: for each tile covered by a primitive, emit
//          colour/depth/shade/texture values per pixel into staging buffers.
//
// TODO: Replace fn main() stub with Naga-transpiled WGSL from rasterizer.comp.
//       Build step: tools/transpile-shaders.sh
//
// Binding layout (group 0):
//   binding(0) - TriangleSetup
//   binding(1) - AttributeSetup
//   binding(2) - DerivedSetup
//   binding(3) - StaticRasterState
//   binding(4) - StateIndices
//   binding(5) - SpanInfoOffsets
//   binding(6) - SpanSetups
//   binding(7) - TMEM (aliased as TMEM16/TMEM8)
//   binding(8) - Output colour buffer
//   binding(9) - Output depth buffer
//   binding(10)- Output shade-alpha buffer
//   binding(11)- Output coverage buffer
// Push constants → group(2) binding(0)

struct TriangleSetupEntry   { data: array<u32, 32>, }
struct AttributeSetupEntry  { data: array<u32, 32>, }
struct DerivedSetupEntry    { data: array<u32, 16>, }
struct StaticRasterEntry    { data: array<u32,  8>, }
struct StateIndexEntry      { data: array<u32,  4>, }
struct SpanInfoOffsetEntry  { data: array<u32,  4>, }
struct SpanSetupEntry       { data: array<u32, 16>, }
struct TMEMInstance         { data: array<u32, 512>, }  // 2048 u16 as 1024 u32

struct RasterRegisters {
    fb_addr_index       : u32,
    fb_depth_addr_index : u32,
    fb_width            : u32,
    fb_height           : u32,
    primitive_count     : u32,
    _pad0               : u32,
    _pad1               : u32,
    _pad2               : u32,
}

@group(0) @binding(0)  var<storage, read>        triangle_setup  : array<TriangleSetupEntry>;
@group(0) @binding(1)  var<storage, read>        attribute_setup : array<AttributeSetupEntry>;
@group(0) @binding(2)  var<storage, read>        derived_setup   : array<DerivedSetupEntry>;
@group(0) @binding(3)  var<storage, read>        static_raster   : array<StaticRasterEntry>;
@group(0) @binding(4)  var<storage, read>        state_indices   : array<StateIndexEntry>;
@group(0) @binding(5)  var<storage, read>        span_offsets    : array<SpanInfoOffsetEntry>;
@group(0) @binding(6)  var<storage, read>        span_setups     : array<SpanSetupEntry>;
@group(0) @binding(7)  var<storage, read>        tmem_instances  : array<TMEMInstance>;
@group(0) @binding(8)  var<storage, read_write>  color_buf       : array<u32>;
@group(0) @binding(9)  var<storage, read_write>  depth_buf       : array<i32>;
@group(0) @binding(10) var<storage, read_write>  shade_alpha_buf : array<u32>;
@group(0) @binding(11) var<storage, read_write>  coverage_buf    : array<u32>;

@group(2) @binding(0) var<uniform> regs: RasterRegisters;

@compute @workgroup_size(8, 8, 1)
fn main(
    @builtin(global_invocation_id) gid: vec3<u32>,
    @builtin(workgroup_id)         wg_id: vec3<u32>,
) {
    // STUB: Full implementation generated by tools/transpile-shaders.sh from rasterizer.comp
    _ = gid;
    _ = wg_id;
}
