// Skeleton for span_setup.comp (paraLLEl-RDP)
//
// PURPOSE: Convert rasterised triangle edge data into per-scanline span descriptors.
//          One workgroup thread per triangle.
//
// TODO: Replace fn main() stub with Naga-transpiled WGSL from span_setup.comp.
//       Build step: tools/transpile-shaders.sh
//
// Binding layout (group 0):
//   binding(0) - TriangleSetup  (per-primitive edge setup data)
//   binding(1) - AttributeSetup (per-primitive shade/texture/z attributes)
//   binding(2) - ScissorState   (per-primitive scissor rectangle)
//   binding(3) - SpanSetups     (output: per-span descriptors, one per scanline per tri)
// group(1) binding(0) - Interpolation jobs texture buffer
//   (GLSL: layout(set=1,binding=0) uniform utextureBuffer uInterpolationJobs)
//   WGSL: storage buffer of u32 (texture buffers not supported; read as flat array)

// TriangleSetup layout (128 bytes, tightly packed i32/u32 fields)
// Matches TriangleSetupMem from data_structures.h.
struct TriangleSetupEntry {
    data: array<u32, 32>,
}
struct AttributeSetupEntry {
    data: array<u32, 32>,
}
struct ScissorStateEntry {
    data: array<u32, 4>,
}
struct SpanSetupEntry {
    data: array<u32, 16>,
}

@group(0) @binding(0) var<storage, read>       triangle_setup: array<TriangleSetupEntry>;
@group(0) @binding(1) var<storage, read>       attribute_setup: array<AttributeSetupEntry>;
@group(0) @binding(2) var<storage, read>       scissor_state: array<ScissorStateEntry>;
@group(0) @binding(3) var<storage, read_write> span_setups: array<SpanSetupEntry>;
@group(1) @binding(0) var<storage, read>       interpolation_jobs: array<u32>;

@compute @workgroup_size(64, 1, 1)
fn main(
    @builtin(global_invocation_id) gid: vec3<u32>,
) {
    // STUB: Full implementation generated by tools/transpile-shaders.sh from span_setup.comp
    _ = gid;
}
