// Skeleton for tile_binning_combined.comp (paraLLEl-RDP)
//
// PURPOSE: Fine-grained tile binning — determines which primitives touch each
//          8x8 (or 16x16) screen tile. Output drives the ubershader dispatch.
//
// TODO: Replace fn main() stub with Naga-transpiled WGSL from tile_binning_combined.comp.
//       Build step: tools/transpile-shaders.sh
//
// Binding layout (group 0):
//   binding(0) - TriangleSetup  (per-primitive geometry)
//   binding(1) - ScissorState
//   binding(2) - StateIndices   (InstanceIndicesMem)
//   binding(3) - TileBitmask    (output: fine per-tile bitmask, u32[])
//   binding(4) - TileBitmaskCoarse (output: coarse tile bitmask)
//   binding(5) - TileInstanceOffset (output: tile instance start offsets)
// Push constants replacement → group(2) binding(0)

struct ScissorStateEntry {
    data: array<u32, 4>,
}
struct TriangleSetupEntry {
    data: array<u32, 32>,
}
struct StateIndexEntry {
    data: array<u32, 4>,
}

struct TileBinRegisters {
    tile_width          : u32,
    tile_height         : u32,
    max_primitives      : u32,
    max_width           : u32,
    tile_instance_stride: u32,
    scale_factor        : u32,
    _pad0               : u32,
    _pad1               : u32,
}

@group(0) @binding(0) var<storage, read>        triangle_setup      : array<TriangleSetupEntry>;
@group(0) @binding(1) var<storage, read>        scissor_state       : array<ScissorStateEntry>;
@group(0) @binding(2) var<storage, read>        state_indices       : array<StateIndexEntry>;
@group(0) @binding(3) var<storage, read_write>  tile_bitmask        : array<u32>;
@group(0) @binding(4) var<storage, read_write>  tile_bitmask_coarse : array<u32>;
@group(0) @binding(5) var<storage, read_write>  tile_instance_offset: array<u32>;

@group(2) @binding(0) var<uniform> regs: TileBinRegisters;

@compute @workgroup_size(64, 1, 1)
fn main(
    @builtin(workgroup_id)           wg_id    : vec3<u32>,
    @builtin(local_invocation_index) local_idx: u32,
) {
    // STUB: Full implementation generated by tools/transpile-shaders.sh from tile_binning_combined.comp
    _ = wg_id;
    _ = local_idx;
}
