// Skeleton for tmem_update.comp (paraLLEl-RDP)
//
// PURPOSE: Upload texture data from VRAM (RDRAM) into per-draw-call TMEM snapshots.
//          One workgroup handles one texture upload operation.
//
// TODO: Replace fn main() stub with Naga-transpiled WGSL from tmem_update.comp.
//       Build step: tools/transpile-shaders.sh
//
// Binding layout (mirrors GLSL set 0):
//   group(0) binding(0) - VRAM as u32 array (aliased as u8/u16/u32 in GLSL)
//   group(0) binding(1) - TMEM u16 data (2048 entries)
//   group(0) binding(2) - Per-instance TMEM snapshots (array of 2048 u16 each)
// Uniform buffer (push_constant replacement):
//   group(2) binding(0) - Registers { num_uploads: i32 }
// Upload info array (set 1 in GLSL, stored as structured UBO here):
//   group(1) binding(0) - UploadInfoArray

struct UploadInfo {
    width               : i32,
    height              : i32,
    min_t_mod           : f32,
    max_t_mod           : f32,
    vram_addr           : i32,
    vram_width          : i32,
    vram_size           : i32,
    vram_effective_width: i32,
    tmem_offset         : i32,
    tmem_width          : i32,
    tmem_height         : i32,
    mode                : i32,   // UPLOAD_MODE_TILE/TLUT/BLOCK
    fmt                 : i32,   // TEXTURE_FMT_RGBA/YUV/CI/IA/I
    bpp_log2            : i32,
    palette_offset      : i32,
    _pad                : i32,
}

struct UploadInfoArray {
    items: array<UploadInfo, 256>,
}

struct TmemRegisters {
    num_uploads: i32,
    _pad0: i32,
    _pad1: i32,
    _pad2: i32,
}

@group(0) @binding(0) var<storage, read>        vram_u32  : array<u32>;
@group(0) @binding(1) var<storage, read_write>  tmem16    : array<u32>;
@group(0) @binding(2) var<storage, read_write>  tmem_instances: array<u32>;

@group(1) @binding(0) var<uniform> upload_info: UploadInfoArray;
@group(2) @binding(0) var<uniform> regs: TmemRegisters;

@compute @workgroup_size(64, 1, 1)
fn main(
    @builtin(workgroup_id)           wg_id    : vec3<u32>,
    @builtin(local_invocation_index) local_idx: u32,
) {
    // STUB: Full implementation generated by tools/transpile-shaders.sh from tmem_update.comp
    // When this stub is active, TMEM uploads are no-ops and textured polygons
    // will render with incorrect/garbage texture data.
    _ = wg_id;
    _ = local_idx;
}
