// Skeleton for ubershader.comp (paraLLEl-RDP)
//
// PURPOSE: Combined rasteriser + depth + blend in a single monolithic dispatch.
//          Used instead of the split rasterizer/depth_blend passes when the
//          UBERSHADER compile-time variant is selected (default for 1× rendering).
//
// TODO: Replace fn main() stub with Naga-transpiled WGSL from ubershader.comp.
//       Build step: tools/transpile-shaders.sh
//
// NOTE: This is the most complex shader in paraLLEl-RDP (~8000+ lines of GLSL
//       after all #includes are expanded).  Subgroup operations, specialization
//       constants, and push constants are all used.  Manual porting is impractical;
//       automated Naga transpilation is required.
//
// Binding layout — group(0) (from data_structures_buffers.h set=0):
//   binding(0) - VRAM    (storage u32[])
//   binding(1) - HiddenVRAM (storage u32[])
//   binding(2) - TMEM    (storage u32[])
// group(1) — 14 bindings:
//   binding(0)  TriangleSetup[]
//   binding(1)  AttributeSetup[]
//   binding(2)  DerivedSetup[]
//   binding(3)  ScissorState[]
//   binding(4)  StaticRasterState[]
//   binding(5)  DepthBlendState[]
//   binding(6)  StateIndices[]
//   binding(7)  TileInfo[]
//   binding(8)  SpanSetups[]
//   binding(9)  SpanOffsets[]
//   binding(10) BlenderLUT  (u32[])
//   binding(11) TileBinning (fine, u32[])
//   binding(12) TileBinningCoarse (u32[])
// group(2) — GlobalConstants UBO
// Push constants → group(3) binding(0)

struct UbershaderRegs {
    fb_addr_index       : u32,
    fb_depth_addr_index : u32,
    fb_width            : u32,
    fb_height           : u32,
    group_mask          : u32,
    _pad0               : u32,
    _pad1               : u32,
    _pad2               : u32,
}

// --- group 0: VRAM/TMEM ---
@group(0) @binding(0) var<storage, read_write> rdram       : array<u32>;
@group(0) @binding(1) var<storage, read_write> hidden_rdram: array<u32>;
@group(0) @binding(2) var<storage, read_write> tmem        : array<u32>;

// --- group 1: RDP pipeline state buffers ---
@group(1) @binding(0)  var<storage, read> triangle_setup  : array<u32>;
@group(1) @binding(1)  var<storage, read> attribute_setup : array<u32>;
@group(1) @binding(2)  var<storage, read> derived_setup   : array<u32>;
@group(1) @binding(3)  var<storage, read> scissor_state   : array<u32>;
@group(1) @binding(4)  var<storage, read> static_raster   : array<u32>;
@group(1) @binding(5)  var<storage, read> depth_blend_state: array<u32>;
@group(1) @binding(6)  var<storage, read> state_indices   : array<u32>;
@group(1) @binding(7)  var<storage, read> tile_info       : array<u32>;
@group(1) @binding(8)  var<storage, read> span_setups     : array<u32>;
@group(1) @binding(9)  var<storage, read> span_offsets    : array<u32>;
@group(1) @binding(10) var<storage, read> blender_lut     : array<u32>;
@group(1) @binding(11) var<storage, read> tile_binning    : array<u32>;
@group(1) @binding(12) var<storage, read> tile_binning_coarse: array<u32>;

// --- group 2: Global constants ---
@group(2) @binding(0) var<uniform> global_constants: array<vec4<u32>, 16>;

// --- group 3: Push-constant replacement ---
@group(3) @binding(0) var<uniform> regs: UbershaderRegs;

@compute @workgroup_size(8, 8, 1)
fn main(
    @builtin(global_invocation_id) gid   : vec3<u32>,
    @builtin(workgroup_id)         wg_id : vec3<u32>,
) {
    // STUB: Full implementation generated by tools/transpile-shaders.sh from ubershader.comp
    _ = gid;
    _ = wg_id;
}
